### ISSUE TITLE
include information about backups/restores and upgrades

### ISSUE THREAD

**Issue by sioutisc** [espocrm/espocrm-installer#3]
This installer is very convenient to get espocrm up and running. But we need to know how to create backups and restore an instance as required. Also, need to know how to upgrade to newer versions of the system whilst keeping the data intact. The documentation on the espocrm website doesn't work because it assumes that the system is running on the base os rather than containers.

**Comment by tmachyshyn** [comment]
There information are available in the docs:
- [Backup](https://docs.espocrm.com/administration/installation-by-script/#backup)
- [Restore](https://docs.espocrm.com/administration/installation-by-script/#restore)
- [Upgrade](https://docs.espocrm.com/administration/installation-by-script/#espocrm-upgrade)
