### ISSUE TITLE
External access to mysql via SSH after install

### ISSUE THREAD

**Issue by relyd** [espocrm/espocrm-installer#4]
Suggestion: 

After running the install script, you may want to do DB management over an SSH tunnel.

For this you will need to add 

```
ports:
  - 127.0.0.1:3306:3306
```

to 
`/var/www/espocrm/docker-compose.yml`

and issue a 
`./command.sh build`

This allows you to use tools like HeidiSQL over SSH to the docker host.

This could be an installation option e.g. --mysqltunnel that would allow that during install

**Comment by tmachyshyn** [comment]
Hello,

Thanks for your suggestion. 
After looking deeply into this feature, there are no good tools to modify the .yml file via the command line. That's why we cannot implement this feature.

If you have any specific solutions, we would be happy to consider them.

**Comment by tmachyshyn** [comment]
You are free to do it manually after the installation.
