### ISSUE TITLE
Install.sh  fails on  Linux Mint 21.3

### ISSUE THREAD

**Issue by mhmoran** [espocrm/espocrm-installer#7]
**Describe the bug**
Fresh install on Linux Mint 21.3,  sudo bash install.sh  fails with  cat: /etc/upstream-release: Is a directory

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Fresh install of Linux Mint 21.3
2. wget https://github.com/espocrm/espocrm-installer/releases/latest/download/install.sh
3. sudo bash install.sh

**Expected behavior**
The install script to recognize  that it is running on a Linux Mint 21.3 system and appropriately determine the information
it needs from the /etc/upstream-release directory

**Screenshots**

**EspoCRM version**
Specify the EspoCRM version (or versions) on which the bug occurs.
Fresh pull of Espo 8.1.4
![Espo_ss](https://github.com/espocrm/espocrm/assets/10239911/c2d9bb78-61a6-4d0b-83cd-e322c9d17cec)

**Additional context**

**Comment by yurikuzn** [comment]
The Mint OS is not supported. Not a bug. It was added to the docs by a mistake.

**Comment by mhmoran** [comment]
Except that the documentation explicitly states that "Linux Mint" is a 
supported OS.

The problem is  that this piece of code:

  local linuxString=$(cat /etc/*release | grep ^NAME | tr -d 'NAME="' | 
tr '[:upper:]' '[:lower:]')

  declare -a linuxOsList=(centos redhat fedora ubuntu debian mint)

To me, it says that Linux Mint is is a supported OS ...

    NAME="Linux Mint"   -- which is the right string

The  tr -d 'Name="'  returns the string  -- Linux int -- Which is too 
long and int doesn't match any of the names in
the linuxOsList

Mike

**Comment by tmachyshyn** [comment]
@mhmoran after deep investigating we added support Linux Mint.
So, please use the documentation for the installation, https://docs.espocrm.com/administration/installation-by-script/ .
